#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
echo -e "\e[96m Adding PPA  \e[39m"
sudo add-apt-repository -y ppa:ondrej/apache2
sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get update
echo -e "\e[96m Installing apache  \e[39m"
sudo apt-get -y install apache2
echo -e "\e[96m Installing php  \e[39m"
sudo apt-get -y install php7.3 libapache2-mod-php7.3
sudo apt-get -y install curl zip unzip php7.3-mysql php7.3-curl php7.3-json php7.3-mbstring php7.3-gd php7.3-intl php7.3-xml php7.3-zip php-gettext php7.3-pgsql php7.3-bcmath php7.3-redis
#sudo apt-get -y install php-xdebug
sudo phpenmod curl
sudo a2enmod rewrite
sudo a2enmod ssl
sudo a2enmod headers
echo -e "\e[96m Restart apache server to reflect changes  \e[39m"
sudo service apache2 restart
echo -e "\e[96m Installing mysql server \e[39m"
echo "mysql-server-5.7 mysql-server/root_password password root" | sudo debconf-set-selections
echo "mysql-server-5.7 mysql-server/root_password_again password root" | sudo debconf-set-selections
sudo apt-get -y install mysql-server-5.7
echo -e "\e[96m Installing composer \e[39m"
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
echo -e "\e[96m Begin silent install phpMyAdmin \e[39m"
echo -e "\e[93m User: root, Password: root \e[39m"
sudo debconf-set-selections <<< 'phpmyadmin phpmyadmin/dbconfig-install boolean true'
sudo debconf-set-selections <<< 'phpmyadmin phpmyadmin/app-password-confirm password root'
sudo debconf-set-selections <<< 'phpmyadmin phpmyadmin/mysql/admin-pass password root'
sudo debconf-set-selections <<< 'phpmyadmin phpmyadmin/mysql/app-pass password root'
sudo debconf-set-selections <<< 'phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2'﻿
sudo apt-get -y install phpmyadmin
ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin
sudo service apache2 restart
echo -e "\e[92m phpMyAdmin installed successfully \e[39m"
echo -e "\e[92m Remember: password for root user is root \e[39m"
